public enum ErrorCategory
{
    // Validators config
    CONFIG_USER_NOT_EXISTING,
    CONFIG_EXCEPTION,

    // Validators body
    REQUEST_BODY_REQUIRED,
    REQUEST_BODY_NOT_JSON,
    REQUEST_BODY_INVALID_JSON,
    REQUEST_BODY_REQUIRED_FIELDS_MISSING,
    REQUEST_BODY_WRONG_DATATYPES,
    REQUEST_BODY_ERROR,

    // Validator Query String
    REQUEST_QUERY_WRONG_DATATYPES,
    REQUEST_PAGE_INVALID_SORT_FIELDS,
    REQUEST_PAGE_PAGE_MIN,
    REQUEST_PAGE_LIMIT_MIN,
    REQUEST_PAGE_LIMIT_MAX,
    REQUEST_PAGE_INVALID_PAGE,
    REQUEST_PAGE_INVALID_LIMIT,
    REQUEST_PAGE_INVALID_SORT_QUERY,
    REQUEST_QUERY_ERROR,

    //User
    USER_USERNAME_MIN,
    USER_USERNAME_MAX,
    USER_NAME_EMPTY,
    USER_NAME_MAX,
    USER_PASSWORD_MIN,
    USER_ALREADY_EXISTS,
    USER_FAIL_CREATING,
    USER_DOES_NOT_EXISTS,
    USER_FAIL_UPDATING,

    //Token
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    TOKEN_INVALID_CREDENTIALS,
    TOKEN_INVALID_GRANT_TYPE,
    TOKEN_GRANT_TYPE_PASSWORD_MISSING_REQUIRED_FIELDS,
    TOKEN_GRANT_TYPE_REFRESH_TOKEN_MISSING_REQUIRED_FIELDS,
    TOKEN_REQUIRED,
    TOKEN_INVALID_AUTH,

    //Tags
    TAG_NAME_EMPTY,
    TAG_NAME_MAX,
    TAG_DESCRIPTION_MAX,
    TAG_NOT_EXISTS,
    TAG_FAIL_CREATING,
    TAG_FAIL_UPDATING,
    TAG_FAIL_DELETING,

    //Categories
    CATEGORY_NAME_EMPTY,
    CATEGORY_NAME_MAX,
    CATEGORY_DESCRIPTION_MAX,
    CATEGORY_NOT_EXISTS,
    CATEGORY_FAIL_CREATING,
    CATEGORY_FAIL_UPDATING,
    CATEGORY_FAIL_DELETING,
    CATEGORY_PARENT_NOT_EXISTS,
    CATEGORY_PARENT_IS_SUBCATEGORY,
    CATEGORY_SELF_PARENT,
    CATEGORY_PARENT_CAN_NOT_BE_SUBCATEGORY,

    //Record Items
    RECORD_ITEM_NOTE_MAX,

    /*
    CATEGORY_NOT_EXISTS,
    CATEGORY_FAIL_CREATING,
    CATEGORY_FAIL_UPDATING,
    CATEGORY_FAIL_DELETING,
    CATEGORY_PARENT_NOT_EXISTS,
    CATEGORY_PARENT_IS_SUBCATEGORY,
    CATEGORY_SELF_PARENT,
    CATEGORY_PARENT_CAN_NOT_BE_SUBCATEGORY,*/

    //Records
    RECORD_DESCRIPTION_MAX,
    RECORD_DATE_IS_ON_FUTURE,
    RECORD_STATUS_UNKNOWN,
    RECORD_FAIL_CREATING,
    
}